# Generated by Django 3.0.6 on 2020-12-16 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Event_app', '0003_auto_20201214_0123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['comment_date']},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-publish_date']},
        ),
    ]
