# Generated by Django 3.1.4 on 2020-12-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event_app', '0004_auto_20201216_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
