# Generated by Django 3.1.4 on 2020-12-18 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Event_app', '0005_event_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
    ]
