# Generated by Django 3.1.4 on 2020-12-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event_app', '0006_remove_event_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='End_Date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
