# Generated by Django 3.1.4 on 2020-12-22 19:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Event_app', '0007_event_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='End_Date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 12, 22, 19, 14, 58, 579975, tzinfo=utc), verbose_name='End_Date(mm/dd/year)'),
            preserve_default=False,
        ),
    ]
