# Generated by Django 3.1.4 on 2020-12-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event_app', '0008_auto_20201223_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='End_Date',
            field=models.DateField(blank=True),
        ),
    ]
