# Generated by Django 3.1.4 on 2020-12-22 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event_app', '0009_auto_20201223_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='End_Date',
            field=models.DateField(),
        ),
    ]
