# Generated by Django 3.1.4 on 2020-12-22 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Event_app', '0010_auto_20201223_0215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='End_Date',
        ),
    ]
