# Generated by Django 3.1.4 on 2020-12-22 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Event_app', '0011_remove_event_end_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-comment_date']},
        ),
    ]
