# Generated by Django 3.1.4 on 2020-12-22 21:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Event_app', '0012_auto_20201223_0240'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='likes',
            new_name='Like',
        ),
    ]
