# Generated by Django 3.1.4 on 2020-12-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event_app', '0013_auto_20201223_0301'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='End_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
