# Generated by Django 3.1.4 on 2020-12-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event_app', '0014_event_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='End_date',
            field=models.DateField(blank=True, null=True, verbose_name=' End_date(mm/dd/year)'),
        ),
    ]
