# Generated by Django 3.1.4 on 2021-01-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event_app', '0015_auto_20201225_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Start_date',
            field=models.DateField(blank=True, null=True, verbose_name=' End_date(mm/dd/year)'),
        ),
    ]
